#!/bin/bash
#
# This script should be executed on a Seagate
# Central on startup before the samba service is
# started.
#
# It checks to see if the original version 3.x.x
# samba is running.
#
# If not it tries to copy an alternate smb.conf
# samba configuration file into place that works
# properly with more recent versions of samba.
#
SAMBA_VERSION=$(testparm -V)
SAMBA_VERSION_3=$(echo $SAMBA_VERSION | grep "ersion 3")
if [ -z $SAMBA_VERSION_3 ]; then
    echo "Samba $SAMBA_VERSION running. Using new samba configuration"
    cp /etc/samba/smb.conf.v4 /etc/samba/smb.conf
fi

