#!/bin/bash
#
# This script should be executed on a Seagate
# Central during startup before the
# /etc/rcS.d/S99finish
# script.
#
# If the root password is currently blank or setup
# only using the /etc/passwd file it sets
# it to the value specified below in the script.
#
# If a root password is already set then this
# script has no impact and will not change the
# current root password.
#
if ! grep -q "^root:x:" /etc/passwd
then
    #clear out root pw in /etc/passwd
    sed "s#^root:.*#root:x:0:0:root:/home/root:/bin/sh#" -i /etc/passwd
    
    # The value below should have been set by the firmware creation script
    echo "root:XXXXXXXXXX" | chpasswd

    # Copy the changes to the Central's backup config folder.
    rsync -Rva /etc/passwd /usr/config/backupconfig
    rsync -Rva /etc/shadow /usr/config/backupconfig
fi
	
