#!/bin/bash
#
# This script should be executed on a Seagate
# Central during startup before the
# /etc/rcS.d/S99finish
# script.
#
# If the root password is currently blank it sets
# it to the value specified below in the script.
#
# This value should have been randomly generated
# when the firmware was built.
#
# If a root password is already set then this
# script has no impact and will not change the
# current root password.
#
if grep -q "^root:x:" /etc/passwd
then
      echo "root:XXXXXXXXXX" | chpasswd
      # Make sure the changes are in the Central's backup config folder.
      rsync -Rva /etc/passwd /usr/config/backupconfig
fi
	